#!/usr/bin/env bash
# Updates the current state of the server
# Installs Nginx on the server
# Configures custom 404 and redirection pages
# Restarts Nginx

# Update package lists and install Nginx
apt-get -y update
apt-get install -y nginx

# Overwrite the default Nginx page (optional)
echo "Holberton School for the win!" > /var/www/html/index.html

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Update the Nginx configuration file
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    # Redirection location
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=7qZl_5xHoBw&t=1358s&ab_channel=PowerfulJRE;
    }

    # A location that intentionally returns a 404 for testing
    location /xyz {
        return 404;
    }

    # Custom error page for 404
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Restart Nginx to apply the changes
sudo service nginx restart
 
